name: "Build and Release Android app"
on:
    push:
        branches:
            - feat/cd-workflow
        tags:
            - v*
permissions:
    contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "18" 
          distribution: "adopt"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install -g corepack
          yarn install

      - name: Build release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/release/app-release.apk

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Release
        id: create_release
        run: |
          tag=$(echo "${GITHUB_REF#refs/tags/}")
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag}" \
            --generate-notes
        shell: bash
        
  upload_asset:
    name: Upload APK to GitHub Release
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Download Release URL
        id: get_release_url
        run: echo "::set-output name=upload_url::$(gh release view ${{ github.repository }} ${GITHUB_REF#refs/tags/} --json upload_url -q)"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: react-native-template.apk
          asset_content_type: application/vnd.android.package-archive
