name: "Build and Release Android app"
on:
    push:
        branches:
            - feat/cd-workflow
        tags:
            - v*
permissions:
    contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "18" 
          distribution: "adopt"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install -g corepack
          yarn install

      - name: Build release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        id: create_release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
        run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes
          
      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: react-native-template.apk
          asset_content_type: application/vnd.android.package-archive
